### ISSUE TITLE
mud map

### ISSUE THREAD

**Issue by mdsumner** [r-gris/table-r-book#1]
https://github.com/r-gris/table-r-book/blob/master/01-2-overview.Rmd

https://www.r-consortium.org/blog/2016/12/06/call-for-proposals

https://github.com/edzer/sfr/blob/master/PROPOSAL.md

https://github.com/environmentalinformatics-marburg/mapview_toolchain/blob/master/mapview_interactive_data_manipulation.Rmd

**Comment by jessmt** [comment]
I read https://github.com/r-gris/table-r-book/blob/master/01-2-overview.Rmd. Not sure I understood, but I think it's understandable. It's really good. Not sure if this is the right way to comment.
The last three sections with details on nested data frames, the relational view, and beyond were pretty much beyond me.
